name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_mac:
    name: Build macOS artifact
    uses: ./.github/workflows/build_mac.yml
    secrets:
      CERT_P12_BASE64: ${{ secrets.CERT_P12_BASE64 }}
      CERT_PASS: ${{ secrets.CERT_PASS }}
  build_win64:
    name: Build Win64 artifact
    uses: ./.github/workflows/build_win64.yml

  release:
    name: Attach release artifacts
    needs: [build_mac, build_win64]
    runs-on: ubuntu-22.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: prev-tag
        run: |
          git fetch -a
          echo "prev_tag=$(git describe --tags ${{ github.ref_name }}^)" >> "$GITHUB_OUTPUT"

      - name: Get tag names
        run: |
          echo "steps.prev-tag.outputs.prev_tag: ${{ steps.prev-tag.outputs.prev_tag }}"
          echo "github.ref_name: ${{ github.ref_name }}"

      - name: Get changelog
        id: changelog
        run: |
          echo "commits=$(git log --pretty=format:"* %s" ${{ steps.prev-tag.outputs.prev_tag }}...${{ github.ref_name }})" >> "$GITHUB_OUTPUT"

      - name: Create release draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          body: |
            A user-friendly application that performs port knocking by sending UDP packets to specified ports then checks the status of a TCP port to verify its availability.

            ${{ steps.changelog.outputs.commits }}

            **Full Changelog**: ${{ github.server_url }}/${{ github.repository }}/compare/${{ steps.prev-tag.outputs.prev_tag }}...${{ github.ref_name }}

      - name: Download macOS build artifact
        uses: actions/download-artifact@v4
        with:
          name: port-knocking-app-macOS-universal
          path: ./artifacts/macos

      - name: Download Windows build artifact
        uses: actions/download-artifact@v4
        with:
          name: port-knocking-app-win64-installer
          path: ./artifacts/windows

      - name: Get filenames
        id: get_filenames
        run: |
          echo "macos_binary=$(find ./artifacts/macos -type f -name '*.dmg' -exec basename {} \;)" >> "$GITHUB_OUTPUT"
          echo "windows_binary=$(find ./artifacts/windows/ -type f -name '*.exe' -exec basename {} \;)" >> "$GITHUB_OUTPUT"

      - name: Upload macOS artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './artifacts/macos/${{ steps.get_filenames.outputs.macos_binary }}'
          asset_name: 'port-knocking-app-${{ github.ref_name }}-macOS-universal.dmg'
          asset_content_type: application/octet-stream

      - name: Upload Windows artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/windows/squirrel.windows/x64/${{ steps.get_filenames.outputs.windows_binary }}
          asset_name: port-knocking-app-${{ github.ref_name }}-win64-installer.exe
          asset_content_type: application/octet-stream
